import React from "react";
import styles from "../styles/Bookmarks.module.css";
import Head from "next/head";
import Left from "../components/Left";



const About = () => {

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Left />
                <div className={styles.right} style={{ textAlign: "left" }}>
                    <div style={{ fontSize: "200%", fontWeight: "bold" }}>About Us</div>
                    <p>
                        Quran.com was founded in 1995. The website aims to make it easy for
                        anyone to read, study, and learn the Quran. The project is open
                        source and is built as a collaboration between core team members and
                        the Tarteel team.
                    </p>

                    <h2>Credits</h2>
                    <p>
                        Quran.com was founded in 1995. The website aims to make it easy for
                        anyone to read, study, and learn the Quran. The project is open
                        source and is built as a collaboration between core team members and
                        the Tarteel team.
                    </p>
                </div>
            </main>

            <footer className={styles.footer}></footer>
        </div>
    );
};

export default About;
