import React from "react";
import styles from "../styles/Bookmarks.module.css";
import Head from "next/head";
import Left from "../components/Left";
import Card from "../components/Card";
import BookmarkIcon from "@mui/icons-material/Bookmark";
import { useDispatch, useSelector } from "react-redux";
import { useSnackbar } from "notistack";
import SearchBar from "../components/SearchBar";
import { Ichapater, Isurah, Iverse } from "../type";
import { RootState } from "../redux/store";
import { removeFromBookmark } from "../redux/BookmarkSlicer";

const Bookmark = () => {
    const bookmarks: Iverse[] = useSelector((state: RootState) => state.bookmark.bookmarks);
    const bookmarkedSurah: Ichapater[] = useSelector(
        (state: RootState) => state.bookmark.bookmarkedSurah
    );
    const { enqueueSnackbar, closeSnackbar } = useSnackbar();

    const dispatch = useDispatch();
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Left />
                <div className={styles.right}>
                    <SearchBar />
                    <div className={styles.heading}>Bookamarked Surah</div>
                    <div className={styles.surahs}>
                        {bookmarkedSurah.map((surah, index) => (
                            <Card surah={surah} bookmarkedSurah={bookmarkedSurah} key={index} />
                        ))}
                    </div>
                    <div className={styles.heading}>Bookamarked Verses</div>
                    <div className={styles.verses}>
                        {bookmarks.map((item, index) => (
                            <div className={styles.verse} key={index}>
                                <div className={styles.icon}>
                                    <BookmarkIcon
                                        onClick={() => {
                                            dispatch(removeFromBookmark(item));
                                            enqueueSnackbar(`Verse ${item.id} removed from bookmark`);
                                        }}
                                    />
                                </div>
                                <div className={styles.arabic}>{item.content}</div>
                                <div className={styles.eng}>{item.translation_eng}</div>
                                <div className={styles.ref}>{item.id}</div>
                            </div>
                        ))}
                    </div>
                </div>
            </main>

            <footer className={styles.footer}></footer>
        </div>
    );
};

export default Bookmark;
