import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Left from '../components/Left'
import SearchBar from '../components/SearchBar'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { Ichapater } from '../type'
import { useDispatch, useSelector } from "react-redux";
import AllSurah from '../components/AllSurah'
import { RootState } from '../redux/store'
import Card from '../components/Card'
import Popular from '../components/Popular'

const Home = ({ chapters }: { chapters: Ichapater[] }) => {
  const bookmarkedSurah: Ichapater[] = useSelector(
    (state: RootState) => state.bookmark.bookmarkedSurah
  );
  const history: Ichapater[] = useSelector((state: RootState) => state.history.history);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Left />
        <div className={styles.right}>
          <SearchBar />
          <Hero />
          <Popular />

          <div className={styles.recent}>
            <div className={styles.heading}>Recently Bookmarked</div>
            <div className={styles.cards}>
              {bookmarkedSurah.slice(0, 6)?.map((surah, index) => (
                <Card surah={surah} bookmarkedSurah={bookmarkedSurah} key={index} />
              ))}
            </div>
          </div>
          <p></p>

          <div className={styles.recent}>
            <div className={styles.heading}>Recently Read</div>
            <div className={styles.cards}>
              {history.slice(0, 6)?.map((surah, index) => (
                <Card surah={surah} bookmarkedSurah={bookmarkedSurah} key={index} />
              ))}
            </div>
          </div>


          <AllSurah chapters={chapters} />

        </div>
      </div>



    </div>
  )
}

export default Home

export const getServerSideProps = async () => {
  const res = await axios.get(
    "https://api.quran.com/api/v4/chapters?language=en"
  );


  return {
    props: { chapters: res.data.chapters }, // will be passed to the page component as props
  };
}